accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView



app_name = 'accounts'

urlpatterns = [
    path('login',auth_views.LoginView.as_view(template_name="accounts/login.html",redirect_authenticated_user = True),name='login'),
    path('login_ajax/', views.SignUp.as_view(), name='login_ajax'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.SignUpView.as_view(), name='register')
]

baykar_iha_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLSpython manage.py migrate dashboard
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]




if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('iha/create/', views.IHACreateView.as_view(), name='iha_create'),
    path('iha/list/', views.IHAListView.as_view(), name='iha_list'),
    path('iha/<slug:slug>/detail/', views.IHADetailView.as_view(), name='iha_detail'),
    path('iha/<int:pk>/delete/', views.IHADeleteView.as_view(), name='iha_delete'),    
    path('iha/<slug:slug>/update/', views.IHAUpdateView.as_view(), name='iha_update')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.utils.translation import gettext_lazy as _


class User(AbstractBaseUser):
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['username']

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import User



class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=250, help_text="The email field is required.")

    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

        
    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            user = User.objects.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"The {user.email} mail is already exists")
    
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.get(username = username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"The {user.username} mail is already exists")
    
    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
import json
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic


from accounts.forms import UserRegistrationForm



class SignUp(generic.View):
    def post(self, request, *args, **kwargs):
        logout(request)
        resp = {"status": 'failed', 'msg': ''}
        username = ''
        password = ''

        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    resp['status'] = 'success'
                else:
                    resp['msg'] = "Incorrect username or password"
            else:
                resp['msg'] = "Incorrect username or password"
        return HttpResponse(json.dumps(resp), content_type='application/json')


class LogoutView(generic.View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)

# class LogoutView(generic.Log)

class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')
    form_class = UserRegistrationForm
    success_message = "Your profile was created successfully"

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="vh-100 d-flex justify-content-center align-items-center ">
    <div class="col-md-5 p-5 shadow-sm border rounded-5 border-primary bg-white">
        <h2 class="text-center mb-4 text-primary">Login Form</h2>
        <form id="login-user">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" name="username" id="username" required="required" class="form-control border border-primary" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" class="form-control border border-primary" id="password">
            </div>
            <p class="small"><a class="text-primary" href="forget-password.html">Forgot password?</a></p>
            <div class="d-grid">
                <button class="btn btn-primary" type="submit">Login</button>
            </div>
        </form>
        <div class="mt-3">
            <p class="mb-0  text-center">Don't have an account? <a href="signup.html"
                    class="text-primary fw-bold">Sign
                    Up</a></p>
        </div>
    </div>
</div>
{% endblock %}


{% block js_custom %}
<script>
    $(function() {
        $('#login-user').submit(function(e) {
            e.preventDefault();
            var _this = $(this)
            $('.err-msg').remove();
            var el = $('<div>')
            el.addClass("alert alert-danger err-msg")
            el.hide()
            if (_this[0].checkValidity() == false) {
                _this[0].reportValidity();
                return false;
            }
            $.ajax({
                headers: {
                    "X-CSRFToken": '{{csrf_token}}'
                },
                url: "{% url 'accounts:login_ajax' %}",
                data: new FormData($(this)[0]),
                cache: false,
                contentType: false,
                processData: false,
                method: 'POST',
                type: 'POST',
                dataType: 'json',
                error: err => {
                    console.log(err)
                    alert_toast("An error occured", 'error');
                },
                success: function(resp) {
                    if (typeof(resp) == 'object' && resp.status == 'success') {
                        el.removeClass("alert alert-danger err-msg")
                        location.href = "{% url 'core:home' %}"
                    } else if (resp.status == 'failed' && !!resp.msg) {
                        el.text(resp.msg)
                    } else {
                        el.text("An error occured", 'error');
                        console.err(resp)
                    }
                    _this.prepend(el)
                    el.show('slow')
                }
            })
        })
    })
</script>
{% endblock js_custom %}

templates/accounts/register.html
{% extends 'base.html' %} 
{% load static %}
{% load widget_tweaks %}


{% block custom_css %}
    <link rel="stylesheet" type="" href="{% static 'assets/css/register.css' %}">
{% endblock custom_css %}


{% block content %}
<div class="form-body">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Register Today</h3>
                    <p>Fill in the data below.</p>
                    <form class="requires-validation" action="{% url 'accounts:register' %}" novalidate="" method="POST">
                        {% csrf_token %}
                        <div class="col-md-12 mb-2">
                            <label for="id_username">Username</label>
                            {% if form.username.errors %}
                                {% render_field form.username %}
                                <div class="text-danger">{% for error in form.username.errors %}{{ error }}{% endfor %}</div>
                            {% else %}

                                {% render_field form.username %}
                            {% endif %}
                        </div>
                            
                        <div class="col-md-12 mb-2">
                            <label for="id_email">Email</label>
                            {% if form.email.errors %}
                                {% render_field form.email %}
                                <div class="text-danger">{% for error in form.email.errors %}{{ error }}{% endfor %}</div>
                            {% else %}

                                {% render_field form.email %}
                            {% endif %}
                        </div>
                            
                        <div class="col-md-12 mb-2">
                            <label for="id_password1">Password</label>
                            {% if form.password1.errors %}
                                {% render_field form.password1 %}
                                <div class="text-danger">{% for error in form.password1.errors %}{{ error }}{% endfor %}</div>
                            {% else %}

                                {% render_field form.password1 %}
                            {% endif %}
                        </div>
                            
                        <div class="col-md-12 mb-2">
                            <label for="id_password1">Password confirm</label>
                            {% if form.password2.errors %}
                                {% render_field form.password2 %}
                                <div class="text-danger">{% for error in form.password2.errors %}{{ error }}{% endfor %}</div>
                            {% else %}

                                {% render_field form.password2 %}
                            {% endif %}
                        </div>
                            
                        
                        {% comment %} <div class="col-md-12">
                            <input class="form-control" type="text" name="name" placeholder="Full Name" required="">
                            <div class="valid-feedback">Username field is valid!</div>
                            <div class="invalid-feedback">Username field cannot be blank!</div>
                        </div>

                        <div class="col-md-12">
                            <input class="form-control" type="email" name="email" placeholder="E-mail Address" required="">
                            <div class="valid-feedback">Email field is valid!</div>
                            <div class="invalid-feedback">Email field cannot be blank!</div>
                        </div>


                        <div class="col-md-12">
                            <input class="form-control" type="password" name="password" placeholder="Password" required="">
                            <div class="valid-feedback">Password field is valid!</div>
                            <div class="invalid-feedback">Password field cannot be blank!</div>
                        </div> {% endcomment %}

                        <div class="form-button mt-3">
                            <button id="submit" type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}