baykar_iha_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLSpython manage.py migrate dashboard
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]




if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('iha/create/', views.IHACreateView.as_view(), name='iha_create'),
    path('iha/list/', views.IHAListView.as_view(), name='iha_list'),
    path('iha/<slug:slug>/detail/', views.IHADetailView.as_view(), name='iha_detail'),
    path('iha/<int:pk>/delete/', views.IHADeleteView.as_view(), name='iha_delete'),    
    path('iha/<slug:slug>/update/', views.IHAUpdateView.as_view(), name='iha_update')
]

core/models.py
from email.policy import default
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


class Marka(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Model(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class CategoryIHA(models.Model):
    name = models.CharField('Ad', max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class IHA(models.Model):
    name = models.CharField('Ad', max_length=255)
    weight = models.DecimalField(_("Weight"), max_digits=10, decimal_places=2)

    categories = models.ForeignKey(
        'core.CategoryIHA', related_name='ihas', on_delete=models.CASCADE, blank=True, null=True)
    markas = models.ForeignKey(
        'core.Marka', related_name='ihas', on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(_("slug"), editable=False, unique=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(IHA, self).save(*args, **kwargs)
        self.slug = f'{self.name.lower()}-{self.id}'
        super(IHA, self).save(*args, **kwargs)  # Call the real save() method

    @property
    def get_absolute_url(self):
        """ Returns the detail URL. """
        return reverse("core:iha_detail", kwargs={"slug": self.slug})

templates/ihas/create.html
{% extends 'base.html' %} 
{% block content %} 

{% comment %} <form method="POST" enctype="multipart/form-data">
  <!-- Security token -->
  {% csrf_token %}

  <!-- Using the formset -->
  {{ form.as_p }}

  <input type="submit" value="Submit" />
</form> {% endcomment %}


<div class="container-fluid">
  <h1 class='text-center'>Create IHA</h1>
  <hr />
  <div class="row">
    <div class="col-sm-4 offset-sm-4">
      <form method="POST" >
        {% csrf_token %}

        <div class="form-group">
          <label for="id_name">Name</label>
          {{ form.name }}
          
          {{ form.name.errors }}
        </div>

        <div class="form-group">
          <label for="id_weight">Weight</label>
          {{ form.weight }}
          
          {{ form.weight.errors }}
        </div>

        <div class="form-group">
          <label for="id_categories">Category</label>
          {{ form.categories }}
          
          {{ form.categories.errors }}
        </div>

        <div class="form-group">
          <label for="id_categories">Marka</label>
          {{ form.markas }}
          
          {{ form.markas.errors }}
        </div>
        <div class="d-flex justify-content-center">
          <button type="submit" class="btn btn-primary mt-2 text-right">Submit</button>
        </div>
      </form>
    </div>
  </div>

  
  </form>

</div> 

{% endblock %}

templates/ihas/delete_confirm.html
{% extends 'base.html' %}


{% block content %}

<form method="post">
    {% csrf_token %}

    <p>Are you sure you want to delete "{{ object }}"?</p>

    <input type="submit" value="Confirm" />
</form>

{% endblock %}

templates/ihas/detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Marka</th>
                    <th scope="col">Category</th>
                    <th scope="col">Weight</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>{{ iha.name }}</td>
                    <td>{{ iha.markas }}</td>
                    <td>{{ iha.categories }}</td>
                    <td>{{ iha.weight }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/ihas/update.html
{% extends 'base.html' %} 
{% block content %} 

{% comment %} <form method="POST" enctype="multipart/form-data">
  <!-- Security token -->
  {% csrf_token %}

  <!-- Using the formset -->
  {{ form.as_p }}

  <input type="submit" value="Submit" />
</form> {% endcomment %}


<div class="container-fluid">
  <h1 class='text-center'>IHA-ni update</h1>
  <hr />
  <div class="row">
    <div class="col-sm-4 offset-sm-4">
      <form method="POST" >
        {% csrf_token %}

        <div class="form-group">
          <label for="id_name">Name</label>
          {{ form.name }}
          
          {{ form.name.errors }}
        </div>

        <div class="form-group">
          <label for="id_weight">Weight</label>
          {{ form.weight }}
          
          {{ form.weight.errors }}
        </div>

        <div class="form-group">
          <label for="id_categories">Category</label>
          {{ form.categories }}
          
          {{ form.categories.errors }}
        </div>

        <div class="form-group">
          <label for="id_categories">Marka</label>
          {{ form.markas }}
          
          {{ form.markas.errors }}
        </div>
        <div class="d-flex justify-content-center">
          <button type="submit" class="btn btn-primary mt-2 text-right">Submit</button>
        </div>
      </form>
    </div>
  </div>

  
  </form>

</div> 

{% endblock %}