baykar_iha_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLSpython manage.py migrate dashboard
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]




if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('iha/create/', views.IHACreateView.as_view(), name='iha_create'),
    path('iha/list/', views.IHAListView.as_view(), name='iha_list'),
    path('iha/<slug:slug>/detail/', views.IHADetailView.as_view(), name='iha_detail'),
    path('iha/<int:pk>/delete/', views.IHADeleteView.as_view(), name='iha_delete'),    
    path('iha/<slug:slug>/update/', views.IHAUpdateView.as_view(), name='iha_update')
]

templates/includes/cat_navbar.html
<div class="dropdown me-2">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown"
        aria-expanded="false">
        IHA
    </a>

    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <li><a class="dropdown-item" href="{% url 'core:iha_create' %}">Create IHA</a></li>
        <li><a class="dropdown-item" href="{% url 'core:iha_list' %}">IHA Lists</a></li>
    </ul>
</div>