accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView



app_name = 'accounts'

urlpatterns = [
    path('login',auth_views.LoginView.as_view(template_name="accounts/login.html",redirect_authenticated_user = True),name='login'),
    path('login_ajax/', views.SignUp.as_view(), name='login_ajax'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.SignUpView.as_view(), name='register')
]

baykar_iha_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLSpython manage.py migrate dashboard
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]




if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('iha/create/', views.IHACreateView.as_view(), name='iha_create'),
    path('iha/list/', views.IHAListView.as_view(), name='iha_list'),
    path('iha/<slug:slug>/detail/', views.IHADetailView.as_view(), name='iha_detail'),
    path('iha/<int:pk>/delete/', views.IHADeleteView.as_view(), name='iha_delete'),    
    path('iha/<slug:slug>/update/', views.IHAUpdateView.as_view(), name='iha_update')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    {% block custom_css %}

    {% endblock custom_css %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <title>Document</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:home' %}">Husubayli</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                <div></div>
                <div class="d-flex justify-content-space-between">
                    {% if not request.user.is_authenticated %}
                        <a class="btn btn-primary me-2 nav-item" href="{% url 'accounts:login' %}">Login</a>
                        <a class="btn btn-success me-2 nav-item" href="{% url 'accounts:register' %}">Register</a>
                    {% else %}
                        {% include 'includes/cat_navbar.html' %} 
                        {% comment %} <h3 class="me-3">Welcome {{ request.user.username }}! </h3> {% endcomment %}
                        <a class="btn btn-success me-2 nav-item ml-2" href="{% url 'accounts:logout' %}">Logout</a>
                    {% endif %}
                    
                </div>
                    
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

    {% block js_custom %}

    {% endblock js_custom %}

</body>

</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}
    
{% endblock %}